### ISSUE TITLE
plugin compilation

### ISSUE THREAD

**Issue by Atrolwei** [cgagner/vscode-moos-ivp-editor#1]
Hello, can you provide the compilation method of the plugin or compile a .vsix plugin that can be used for us to download?

**Comment by cgagner** [comment]
I am in the middle of rewriting this VSCode extension to use a backend language server so it can provide better semantic highlighting and diagnostics. That will also allow it to be used in other editors (E.G. Neovim). The rewrite is probably not ready for distribution, but I will hopefully have it cleaned up enough for beta testing in a couple of weeks.

Building the VSCode package is documented here:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Gist:

1. Make sure Node.js is installed.
2. Install the Visual Studio Code Extensions: `npm install -g @vscode/vsce`
3. Change into the project directory.
4. Build the package: `vsce package`

I will update the `README.md` file with these instructions in the next couple of days.

**Comment by Atrolwei** [comment]
Alright, I appreciate your explanation. Thank you!
